apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress
  namespace: emqx
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: emqx
  type: LoadBalancer
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
