apiVersion: v1
kind: Service
metadata:
  name: ilb
  namespace: emqx
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: emqx
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
  - name: dashboard
    protocol: TCP
    port: 18083
    targetPort: 18083
