emqtt_bench_clients_per_node: 500000
emqtt_bench_connect_interval: 10
emqtt_bench_scenario: "sub -c {{ emqtt_bench_clients_per_node }} -i {{ emqtt_bench_connect_interval }} -t bench/%%i -q 2 -n {{ emqtt_bench_start_number * emqtt_bench_clients_per_node }}"
