- hosts: gke
  tasks:
    - name: Tune kernel parameters
      become: yes
      ansible.builtin.shell: |
        sysctl -w net.core.netdev_max_backlog=16384
        sysctl -w net.core.somaxconn=65535
        sysctl -w net.ipv4.ip_local_port_range='1024 65535'
        sysctl -w net.ipv4.tcp_tw_reuse=1
        sysctl -w net.netfilter.nf_conntrack_max=13107200
        sysctl -w net.netfilter.nf_conntrack_tcp_timeout_time_wait=30
        sysctl -w net.nf_conntrack_max=13107200
        sysctl -w fs.file-max=2097152
        sysctl -w fs.nr_open=2097152
