- hosts: loadgen
  vars:
    ip_list: []
    emqtt_bench_clients_per_node: 500000
    emqtt_bench_connect_interval: 5
  pre_tasks:
    - name: Tune kernel parameters
      become: yes
      ansible.builtin.shell: |
        sysctl -w net.ipv4.ip_local_port_range='1024 65535'
        sysctl -w fs.file-max=2097152
        sysctl -w fs.nr_open=2097152
    - name: Install GCP cloud-ops agent
      become: yes
      ansible.builtin.shell: |
        curl -sSO https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
        bash add-google-cloud-ops-agent-repo.sh --also-install
    - name: Generate IP addresses
      set_fact:
        ip_list: "{{ ip_list + [ip_alias_subnet | ansible.utils.ipmath(item)] }}"
      loop: "{{ range(0, ip_alias_count) }}"
  roles:
    - emqtt_bench
